name: Unit tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  doctest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
      
    - name: Install dependencies from Pipfile.lock
      run: pipenv sync --dev --verbose
      
    - name: Run tests
      run: |
        pipenv run python -m doctest -v deadLinkCrawler.py
        
